import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Are you balding?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="p-2.5 min-h-screen h-full bg-royal">
          <div className="border border-royal h-full rounded-[18px] bg-cream relative">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
